### PR TITLE
Fix payout amount overflowing on infinite target (v1 edit payout)

### LINKED ISSUE #1080: Number overflow when distribution limit is infinite and payout is 100%
## Summary

Screen Shot 2022-05-26 at 1 25 28 PM

## Steps to reproduce

1. Go to lunchdao (locally)
2. Click "Edit payouts"
3. Observe.

## What is the _current_ bug behavior?

Number is MAX

## What is the expected _correct_ behavior?

We shouldn't show anything, or we should say "NO LIMIT" or "Infinite" (please experiment)

Please verify the fix works in V1 and V2

### PR DESCRIPTION
**Pull request by johnnyd-eth**
## What does this PR do and why?

Closes #1080 

## Screenshots or screen recordings

Screen Shot 2022-06-01 at 12 46 05 pm

## Acceptance checklist

- [ ] I have evaluated the
      [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines)
      for this PR.
- [ ] I have tested this PR in
      [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

### CODE REVIEW

File: src/components/v1/PayoutModsList.tsx [hunk 1]
```diff
@@ -103,6 +103,9 @@ export default function PayoutModsList({
 
   if (!fundingCycle) return null
 
+  const target = fundingCycle.target
```
Comment (aeolianeth) [inline src/components/v1/PayoutModsList.tsx:106]: **suggestion (non-blocking)**

```suggestion
  const { target } = fundingCycle
```

**Review by aeolianeth — APPROVED** [review]
@johnnyd-eth sweet catch. I had a suggestion but applied it in the interest of efficiency.

Merging!
