### PR TITLE
Fix pay modal custom token beneficiary bug

### LINKED ISSUE #2916: Pay Modal: Custom token beneficiary persist when toggle is turned off
## Summary

The Pay modal contains a switch toggle to turn on Custom token beneficiary. When the Token beneficiary is toggled on and an input is added, if it is then toggled off, the value inside the form still persists. The expected behavior is that the custom token beneficiary should be removed.

## Steps to reproduce

1. Open the Pay modal
2. Turn on the Custom token beneficiary toggle
3. Input a value for the custom token beneficiary
4. Turn off the Custom token beneficiary toggle
5. Observe the persisted value for the custom token beneficiary

## What is the expected _correct_ behavior?

The custom token beneficiary should be removed when the toggle is turned off.

## Relevant logs and/or screenshots

https://user-images.githubusercontent.com/104132113/215668677-84dcf2d8-b342-4583-b6c7-e359c6af143b.mov

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

### PR DESCRIPTION
**Pull request by johnnyd-eth**
## What does this PR do and why?

Closes #2916

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

File: src/components/v2v3/V2V3Project/V2V3PayButton/V2V3ConfirmPayModal/V2V3PayForm.tsx [hunk 1]
```diff
@@ -146,7 +148,12 @@ export const V2V3PayForm = ({
               <Space>
                 <Switch
                   checked={customBeneficiaryEnabled}
-                  onChange={setCustomBeneficiaryEnabled}
+                  onChange={() => {
```
Comment (tomquirk) [inline src/components/v2v3/V2V3Project/V2V3PayButton/V2V3ConfirmPayModal/V2V3PayForm.tsx:151]: **suggstion** think we should still rely on the state value that the component is giving us. WDYT?

```suggestion
                  onChange={(enabled) => {
```

Comment (johnnyd-eth) [reply src/components/v2v3/V2V3Project/V2V3PayButton/V2V3ConfirmPayModal/V2V3PayForm.tsx:151]: Yeah good call, sounds good
