### PR TITLE
1453 project beneficiary fix

### LINKED ISSUE #1453: Payouts to Juicebox projects should have a better handle
## Summary

Payouts and reserved token allocations to other Juicebox projects look shitty.

## Steps to reproduce

1. Go to https://www.juicebox.money/v2/p/1
2. Observe payouts. They use **0x..**

## What is the _current_ bug behavior?

Payouts and reserved token allocations to Juicebox projects use truncated hex notation.

## What is the expected _correct_ behavior?

- If the project has a handle, use the handle
- If the project doesn't have a handle, use **Project :id** (for example, **Project 69**)

### PR DESCRIPTION
**Pull request by jmilldotdev**
## What does this PR do and why?

Closes #1453. On project payout splits for V2 projects, uses project handle if available, and if not converts the projectID from hex notation to int. Currently running parseInt in the component, but could be worth fixing in the useProjectSplits hook.

## Screenshots or screen recordings

image

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

File: src/components/v2/shared/SplitItem.tsx [hunk 1]
```diff
@@ -62,24 +67,33 @@ export default function SplitItem({
...
-            title={<Trans>Juicebox V2 project with ID {split.projectId}</Trans>}
+          <Link
+            href={v2ProjectRoute({ projectId: split.projectId })}
+            target="_blank"
           >
-            <Link
-              href={v2ProjectRoute({ projectId: split.projectId })}
-              target="_blank"
-            >
+            <Tooltip title={getProjectTooltip()}>
```
Comment (tomquirk) [inline src/components/v2/shared/SplitItem.tsx:91]: **question** i seem to recall `Link` needing `<a>` as its direct child. Any particular reason to move the tooltip within?

Comment (tomquirk) [reply src/components/v2/shared/SplitItem.tsx]: Wrapped it in a `span` and made `a` direct child of `link`. Need this so that `a` gets the `href` attribute. Then it behaves like a real link (notice bottom-left of screenshot)


Screen Shot 2022-07-28 at 12 39 36 PM

**Review by tomquirk — APPROVED** [review]
Hell yes @jmilldotdev , long time coming

Approving.
