### PR TITLE
Various small v2 bug fixes

### LINKED ISSUE #882: Change 'Initial issuance...' to 'Current issuance' in token reconfig
## Summary

Screen Shot 2022-04-28 at 5 34 19 pm

Will need to redo these little message about issuance rate, get the current issuance rate instead of using the default 1M

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

### PR DESCRIPTION
**Pull request by johnnyd-eth**
## What does this PR do and why?

1. 'target' -> 'distribution limit' on 'Distributed' tooltip

Screen Shot 2022-04-29 at 9 35 10 pm

2. Prevent 'time until next FC' from counting down in the create flow FC preview

3. Fixes failing deploy/reconfig tx when distribution limit = 'No limit' (changes `MAX_DISTRIBUTION_LIMIT` from maxuint248 to maxuint232)

4. Fixes `distributionLimitCurrency` submitting as 0 by default:
	- This fixes the distribute being blank by default ( '/' ):
	
Screen Shot 2022-04-30 at 2 00 54 pm
	
5. Fixes time until next FC showing as '- -' when it's less than 1min (makes `detailedTimeUntil` round to seconds if the `timeUntil` is less than 2 mins)

6. Hide all the messages about 'initial' token issuance on the reconfig modal since they aren't relavent anymore:

Screen Shot 2022-04-30 at 2 04 40 pm

Screen Shot 2022-04-30 at 2 04 43 pm

Screen Shot 2022-04-30 at 1 42 39 pm

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

Closes #882, #850, #864

### CODE REVIEW

File: src/components/shared/Project/FundingCycleDetailsCard.tsx [hunk 1]
```diff
@@ -36,7 +38,9 @@ export default function FundingCycleDetailsCard({
     const endTimeSeconds = fundingCycleStartTime.add(
       fundingCycleDurationSeconds,
     )
-    const formattedTimeLeft = detailedTimeUntil(endTimeSeconds)
+    const formattedTimeLeft = !isPreviewMode
+      ? detailedTimeUntil(endTimeSeconds)
+      : detailedTimeUntil(fundingCycleDurationSeconds)
```
Comment (johnnyd-eth) [inline src/components/shared/Project/FundingCycleDetailsCard.tsx:43]: Point 2.)

File: src/components/shared/formItems/ProjectReserved.tsx [hunk 2]
```diff
@@ -64,14 +66,16 @@ export default function ProjectReserved({
...
         <>
-          <TabDescription>
-            <Trans>
-              Initial issuance rate will be {formattedNum(initialIssuanceRate)}{' '}
-              tokens / ETH for contributors.{' '}
-              {formattedNum(initialReservedTokensPerEth)} tokens / ETH will be
-              reserved by the project.
-            </Trans>
-          </TabDescription>
+          {isCreate && (
```
Comment (johnnyd-eth) [inline src/components/shared/formItems/ProjectReserved.tsx:69]: 6.) Hide all the messages about 'initial' token issuance on the reconfig modal since they aren't relavent anymore:

File: src/components/v2/V2Create/forms/FundingForm/index.tsx [hunk 3]
```diff
@@ -134,7 +134,8 @@ export default function FundingForm({ onFinish }: { onFinish: VoidFunction }) {
   const resetProjectForm = useCallback(() => {
     const _target = fundAccessConstraint?.distributionLimit ?? '0'
     const _targetCurrency = parseInt(
-      fundAccessConstraint?.distributionLimitCurrency ?? '0',
+      fundAccessConstraint?.distributionLimitCurrency ??
+        V2_CURRENCY_ETH.toString(),
```
Comment (johnnyd-eth) [inline src/components/v2/V2Create/forms/FundingForm/index.tsx:138]: 4.) Fixes distributionLimitCurrency submitting as 0 by default

File: src/components/v2/V2Project/TreasuryStats/DistributedRatio.tsx [hunk 4]
```diff
@@ -63,9 +63,10 @@ export default function DistributedRatio({ style }: { style?: CSSProperties }) {
             <TooltipLabel
               tip={
                 <Trans>
-                  The target for this funding cycle is 0, meaning all funds in
-                  Juicebox are currently considered overflow. Overflow can be
-                  redeemed by token holders, but not distributed.
+                  The distribution limit for this funding cycle is 0, meaning
```
Comment (johnnyd-eth) [inline src/components/v2/V2Project/TreasuryStats/DistributedRatio.tsx:66]: 1.) 'Target' -> 'distribution limit'

**Comment by wraeth-eth** [comment]
> Prevent 'time until next FC' from counting down in the create flow FC preview

Lmao - I actually noticed this one tonight and wasn't sure if a bug or feature 😂

File: src/utils/v2/math.ts [hunk 5]
```diff
@@ -6,16 +6,17 @@ import { WeightFunction } from 'utils/math'
...
+  .div(2 ** 24)
   .sub(1)
 
 export const MAX_RESERVED_RATE = TEN_THOUSAND
 export const MAX_REDEMPTION_RATE = TEN_THOUSAND
 export const MAX_DISCOUNT_RATE = ONE_BILLION
 export const SPLITS_TOTAL_PERCENT = ONE_BILLION
 export const MAX_FEE = ONE_BILLION
-export const MAX_DISTRIBUTION_LIMIT = MaxUint248
+export const MAX_DISTRIBUTION_LIMIT = MaxUint232
```
Comment (johnnyd-eth) [inline src/utils/v2/math.ts:19]: 3.) Fix failing deploy and reconfig on distribution limit = 'no limit'

**Review by wraeth-eth — APPROVED** [review]
LGTM
