### PR TITLE
fix Cancelling transfer tx keeps loading state

### LINKED ISSUE #1581: Cancelling transfer tx keeps loading state
## Summary

Screen Shot 2022-07-28 at 6 01 11 pm

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

### PR DESCRIPTION
**Pull request by benschac**
## What does this PR do and why?
fixes #1581, additionally, any other exceptions thrown during a pending request now just need the `onErorr` callback defined at their callsite, screen shot to follow

Test in vercel preview, both v1 and v2 projects.
## Screenshots or screen recordings
CleanShot 2022-08-11 at 12 07 11

_If applicable, provide screenshots or screen recordings to demonstrate the changes.

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by benschac** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1725** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1725" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1725?utm_source=stack-comment).

File: src/hooks/v1/transactor/SafeTransferFromTx.ts [hunk 1]
```diff
@@ -13,6 +13,24 @@ export function useSafeTransferFromTx(): TransactorInstance<{
 
   return ({ newOwnerAddress }, txOpts) => {
     if (!transactor || !projectId || !contracts?.Projects) {
+      const missingParam = !transactor
```
Comment (benschac) [inline src/hooks/v1/transactor/SafeTransferFromTx.ts:16]: This check should have been here too, just added it to this PR since it was a small change.

Comment (johnnyd-eth) [reply src/hooks/v1/transactor/SafeTransferFromTx.ts:16]: Nice, looks great
