### PR TITLE
Various NFT bugs

### LINKED ISSUE #1789: NFT external link field invalid
## Summary

Screen Shot 2022-08-23 at 2 28 48 pm

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

### LINKED ISSUE #1796: Clicking NFTs while USD selected is broke
## Summary

https://discord.com/channels/775859454780244028/990055537615970384/1011765081131974727

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

### PR DESCRIPTION
**Pull request by johnnyd-eth**
## What does this PR do and why?

1. Selecting an NFT while USD is in pay input results in currency getting switched to ETH (Fixes #1796):

https://user-images.githubusercontent.com/96150256/186561226-29aef56a-02bb-4b38-ae74-cfbd5c7b5818.mp4

2. Fixes external links of older NFT projects (Fixes #1789):
See `/v2/p/4633` when preview link loads. This project was launched before the #1790 fix  

3. Fixes loader being in wrong position when uploading NFTs in create flow (previously sitting too far left)
**Now:**
Screen Shot 2022-08-25 at 12 02 49 pm

4. Removes remaining supply from preview when it is undefined: 
**Before:**
Screen Shot 2022-08-25 at 12 14 35 pm

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

File: src/utils/externalLink.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+// Adds 'https://' to the start of a link if it doesn't already have it
+export function withHttps(link: string | undefined) {
+  if (link?.slice(0, 8) !== 'https://' && link?.slice(0, 7) !== 'http://') {
```
Comment (wraeth-eth) [inline src/utils/externalLink.ts:3]: I think you'll need to test for `link` not being undefined first. I think if it is, you'll always end up with `https://undefined`

File: src/components/v2/V2Project/NftRewardsSection/index.tsx [hunk 2]
```diff
@@ -58,6 +69,20 @@ export function NftRewardsSection({
...
     const nextRewardTier = rewardTiers[index + 1]
 
+    const handleSelected = () => {
+      setSelectedIndex(index)
+      // update pay input with NFT's contribution floor
+      onPayAmountChange(
+        (payInCurrency === USD // convert to USD if USD selected in pay input
+          ? converter
+              .weiToUsd(parseWad(rewardTier.contributionFloor))
+              ?.add(1) //-> adds 1USD to ensure ETH amount is above the contributionFloor
```
Comment (wraeth-eth) [inline src/components/v2/V2Project/NftRewardsSection/index.tsx:79]: ETH can fluctuate way more than $1 very quickly. We should likely add a warning saying something like:
> Paying in USD to secure an NFT can be risky due to volatility. If you want to ensure you secure the NFT, we recommend paying in ETH instead.

And we have this setup to only appear when the user is currently paying enough to receive an NFT.

WDYT?

**Review by wraeth-eth — APPROVED** [review]

File: src/components/v2/V2Project/NftRewardsSection/index.tsx (hunk 2 above)
Comment (wraeth-eth) [reply src/components/v2/V2Project/NftRewardsSection/index.tsx:79]: maybe not saying "paying in eth" but smoething along those lines to convey using eth rather than the converted usd amount

Comment (tomquirk) [reply src/components/v2/V2Project/NftRewardsSection/index.tsx:79]: does it even make sense for tiers to be denominated in USD?

Should we just not allow USD selection if NFT reward selected?

Comment (wraeth-eth) [reply src/components/v2/V2Project/NftRewardsSection/index.tsx:79]: Thing is, they get auto selected so you can’t exactly disable it when an NFT is chosen

File: src/utils/externalLink.ts (hunk 1 above)
Comment (johnnyd-eth) [reply src/utils/externalLink.ts:4]: Great pickup, fixed

File: src/components/v2/V2Project/NftRewardsSection/NftPreview.tsx [hunk 3]
```diff
@@ -67,7 +66,14 @@ export function NftPreview({
 
   if (!visible) return null
 
-  const hasLimitedSupply = rewardTier.remainingSupply !== DEFAULT_NFT_MAX_SUPPLY
+  const hasLimitedSupply = Boolean(
+    rewardTier.remainingSupply &&
```
Comment (johnnyd-eth) [inline src/components/v2/V2Project/NftRewardsSection/NftPreview.tsx:70]: Related to **point 4**

File: src/components/v2/V2Project/NftRewardsSection/NftPreview.tsx [hunk 4]
```diff
@@ -115,7 +121,13 @@ export function NftPreview({
               </div>
             ) : null}
             {rewardTier.externalLink ? (
-              <ExternalLink href={rewardTier.externalLink} style={linkStyle}>
+              <ExternalLink
+                href={rewardTier.externalLink}
+                style={{
+                  ...linkStyle,
```
Comment (johnnyd-eth) [inline src/components/v2/V2Project/NftRewardsSection/NftPreview.tsx:127]: **Point 4**

File: src/components/v2/shared/FundingCycleConfigurationDrawers/NftDrawer/NftRewardTierCard.tsx [hunk 5]
```diff
@@ -114,6 +114,8 @@ export default function NftRewardTierCard({
             display: 'flex',
             justifyContent: 'center',
             alignItems: 'center',
+            height: imageLoading ? NFT_IMAGE_SIDE_LENGTH : 'unset',
```
Comment (johnnyd-eth) [inline src/components/v2/shared/FundingCycleConfigurationDrawers/NftDrawer/NftRewardTierCard.tsx:117]: **Point 3**

File: src/components/v2/shared/FundingCycleConfigurationDrawers/NftDrawer/NftRewardTierCard.tsx [hunk 6]
```diff
@@ -122,8 +124,8 @@ export default function NftRewardTierCard({
           <Image
             src={rewardTier.imageUrl}
             alt={rewardTier.name}
-            height={NFT_IMAGE_SIDE_LENGTH}
-            width={NFT_IMAGE_SIDE_LENGTH}
+            height={imageLoading ? 0 : NFT_IMAGE_SIDE_LENGTH}
```
Comment (johnnyd-eth) [inline src/components/v2/shared/FundingCycleConfigurationDrawers/NftDrawer/NftRewardTierCard.tsx:127]: **Point 3**

File: src/hooks/v2/NftRewards.ts [hunk 7]
```diff
@@ -28,13 +29,13 @@ async function getRewardTierFromIPFS({
...
     description: ipfsRewardTier.description,
-    externalLink: ipfsRewardTier.externalLink,
+    externalLink: withHttps(ipfsRewardTier.externalLink),
     contributionFloor: ipfsRewardTier.attributes.contributionFloor,
     tierRank: index + 1,
     maxSupply: ipfsRewardTier.attributes.maxSupply ?? DEFAULT_NFT_MAX_SUPPLY,
     remainingSupply:
-      contractNftRewardTier.remainingQuantity ??
-      contractNftRewardTier.initialQuantity,
+      contractNftRewardTier.remainingQuantity.toNumber() ??
```
Comment (johnnyd-eth) [inline src/hooks/v2/NftRewards.ts:37]: **Point 4**

File: src/models/v2/nftRewardTier.ts [hunk 8]
```diff
@@ -17,8 +17,8 @@ export type ContractNftRewardTier = {
   id: number
   contributionFloor: BigNumber //uint128
   lockedUntil: BigNumber
-  remainingQuantity: number
-  initialQuantity: number //uint64
+  remainingQuantity: BigNumber
```
Comment (johnnyd-eth) [inline src/models/v2/nftRewardTier.ts:20]: **Point 4**
