### PR TITLE
Fix ProjectHandle input

### LINKED ISSUE #119: Editing payouts from the "reconfigure" page. small bug
When I click to adjust a payout that goes to a project, I have to retype in the project's handle in to the UI.

image

### PR DESCRIPTION
**Pull request by aeolianeth**
Fixes #119, https://github.com/jbx-protocol/juice-interface/issues/189

When editing a payout, the project handle field wasn't populating automatically.

This PR fixes this by:
- Leveraging `Form.Item`'s automatic data binding correctly
- Adding a loading spinner to the project handle input

There's a couple of other unrelated fixes in here, too. I've made comments throughout the PR to highlight these 🙂 .

### Demo

https://user-images.githubusercontent.com/94939382/143811934-5942f732-3a38-43e7-91b3-81efb8f637f8.mp4

### CODE REVIEW

File: src/components/Create/PayModsForm.tsx [hunk 1]
```diff
@@ -51,7 +51,6 @@ export default function PayModsForm({
 
       <Form layout="vertical">
         <FormItems.ProjectPayoutMods
-          name="mods"
```
Comment (aeolianeth) [inline src/components/Create/PayModsForm.tsx:54]: This doesn't need a name. Removing it fixes a console error:

```
Warning: [antd: Form.Item] `children` is array of render props cannot have `name`. 
```

Screen Shot 2021-11-29 at 2 40 07 pm

Comment (aeolianeth) [inline src/components/Create/PayModsForm.tsx:54]: This doesn't need a name. Removing it fixes a console error:

```
Warning: [antd: Form.Item] `children` is array of render props cannot have `name`. 
```

Screen Shot 2021-11-29 at 2 40 07 pm

File: src/components/shared/formItems/ProjectHandle.tsx [hunk 2]
```diff
@@ -80,16 +89,31 @@ export default function ProjectHandle({
...
-  if (handleExists && requireState === 'notExist') {
-    suffix = 'Handle already in use'
-  }
-  if (handleExists === false && requireState === 'exists') {
-    suffix = inputContents ? 'Handle not found' : ''
-  }
-  if (handleExists && requireState === 'exists') {
-    suffix = <CheckCircleOutlined style={{ color: colors.icon.success }} />
-  }
+  const suffix: string | JSX.Element = useMemo(() => {
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectHandle.tsx:92]: Changed `suffix` to memoized value. I _think_ this is a good use case, please correct me if not.

File: src/components/shared/formItems/ProjectHandle.tsx [hunk 3]
```diff
@@ -114,12 +138,12 @@ export default function ProjectHandle({
         placeholder="handle"
         type="string"
         autoComplete="off"
+        spellCheck={false}
         onChange={e => {
           const val = normalizeHandle(e.target.value)
           setInputContents(val)
-
-          if (returnValue !== 'id') {
-            onValueChange(val)
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectHandle.tsx:122]: The parent `Form.Item` is already capturing/handling input value changes.

File: src/components/shared/formItems/ProjectPayoutMods.tsx [hunk 4]
```diff
@@ -419,14 +417,13 @@ export default function ProjectPayoutMods({
             />
           ) : (
             <FormItems.ProjectHandle
-              name="project"
+              name="handle"
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectPayoutMods.tsx:420]: Setting the `name` to `handle` to match the form state variable ensures that the `Form.Item` binds the `input` to the `form` state correctly.

File: src/components/shared/formItems/ProjectPayoutMods.tsx [hunk 5]
```diff
@@ -419,14 +417,13 @@ export default function ProjectPayoutMods({
...
               requireState="exists"
               formItemProps={{
                 label: 'Project handle',
                 rules: [{ required: true }],
               }}
-              value={form.getFieldValue('handle')}
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectPayoutMods.tsx:428]: By setting the `name` correctly above, we don't need to manually retrieve and set the form field 🙂 .

File: src/components/shared/formItems/ProjectHandle.tsx [hunk 6]
```diff
@@ -17,29 +17,32 @@ export default function ProjectHandle({
...
+  initialValue?: string | BigNumber
+  requireState?: 'exists' | 'notExist' // whether the handle is required to already exist or not.
   returnValue?: 'id' | 'handle'
 } & FormItemExt) {
   const {
     theme: { colors },
   } = useContext(ThemeContext)
   const [inputContents, setInputContents] = useState<string>()
-
+  const [handleLoading, setHandleLoading] = useState<boolean>(false)
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectHandle.tsx:33]: Adding a loading state lets us display a spinner in the input field.

Ideally we would debounce the input so we don't re-render every input type. Perhaps this can be a follow-up issue.

File: src/components/shared/formItems/ProjectHandle.tsx [hunk 7]
```diff
@@ -17,29 +17,32 @@ export default function ProjectHandle({
...
   const { contracts } = useContext(UserContext)
 
-  // Value can be either a project ID, or a project's handle
+  // initialValue can be either a project ID, or a project's handle
   useEffect(() => {
-    if (typeof value === 'string') {
-      setInputContents(value)
-    } else if (isBigNumberish(value)) {
+    if (initialValue) {
+      setHandleLoading(true)
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectHandle.tsx:39]: If initialValue is truthy, display the spinner. `idForHandle`'s callback will remove the spinner in its callback fn.

File: src/components/shared/formItems/ProjectHandle.tsx [hunk 8]
```diff
@@ -17,29 +17,32 @@ export default function ProjectHandle({
   hideLabel,
   formItemProps,
   onValueChange,
-  value,
+  initialValue,
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectHandle.tsx:20]: I thought `initialValue` was clearer than `value`. Loosely held opinion, though.

File: src/components/shared/formItems/ProjectHandle.tsx [hunk 9]
```diff
@@ -54,21 +57,27 @@ export default function ProjectHandle({
...
     contract: ContractName.Projects,
     functionName: 'projectFor',
     args: handle && requireState ? [handle] : null,
     callback: useCallback(
-      returnValue === 'id'
-        ? id => onValueChange(id?.toHexString() ?? '0x00')
-        : () => null,
-      [returnValue],
+      id => {
+        setHandleLoading(false)
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectHandle.tsx:67]: Remove the loading spinner once we get an `id` for the handle.

`suffix` (below) will display the correct help text in the input field.

File: src/components/shared/formItems/ProjectPayoutMods.tsx [hunk 10]
```diff
@@ -41,7 +41,6 @@ type ModType = 'project' | 'address'
 type EditingPayoutMod = PayoutMod & { handle?: string }
 
 export default function ProjectPayoutMods({
-  name,
```
Comment (aeolianeth) [inline src/components/shared/formItems/ProjectPayoutMods.tsx:44]: See https://github.com/jbx-protocol/juice-interface/pull/241/files#r758043049

**Comment by aeolianeth** [comment]
Yo @peripheralist, another weird Antd form issue fix  - could you review when you have a chance?

I did my best with local testing, but would appreciate if you could test the other uses of `ProjectHandle`, too 🙏 .

Thanks!

File: src/components/shared/formItems/ProjectHandle.tsx (hunk 6 above)
Comment (peripheralist) [reply src/components/shared/formItems/ProjectHandle.tsx:33]: debouncing would be great here, lots of unnecessary calls right now. we can make that a separate issue

File: src/components/shared/formItems/ProjectHandle.tsx [hunk 11]
```diff
@@ -54,21 +57,27 @@ export default function ProjectHandle({
...
+        if (returnValue === 'id' && onValueChange) {
+          onValueChange(id?.toHexString() ?? '0x00')
+        }
+      },
+      [returnValue, onValueChange],
     ),
   })
 
-  const handleExists = idForHandle?.gt(0)
+  const handleExists = Boolean(idForHandle?.gt(0))
```
Comment (peripheralist) [inline src/components/shared/formItems/ProjectHandle.tsx:76]: what's the purpose here? does `Boolean(x)` convert all falsy values to `false`?

File: src/components/shared/formItems/ProjectHandle.tsx (hunk 2 above)
Comment (peripheralist) [reply src/components/shared/formItems/ProjectHandle.tsx:92]: my understanding is that memoization is kinda subjective—just meant to be used to prevent expensive logic (i.e. network calls or complex calculations) from being run unnecessarily. i'm down to use it here

File: src/components/shared/formItems/ProjectHandle.tsx [hunk 12]
```diff
@@ -114,12 +138,12 @@ export default function ProjectHandle({
         placeholder="handle"
         type="string"
         autoComplete="off"
+        spellCheck={false}
```
Comment (peripheralist) [inline src/components/shared/formItems/ProjectHandle.tsx:141]: 👍

File: src/components/shared/formItems/ProjectHandle.tsx (hunk 11 above)
Comment (aeolianeth) [reply src/components/shared/formItems/ProjectHandle.tsx:76]: > does Boolean(x) convert all falsy values to false?

Exactly 👍

**Comment by aeolianeth** [comment]
Copying comment from issue (https://github.com/jbx-protocol/juice-interface/issues/119#issuecomment-982075205)

> This is looking great, but I'm noticing the issue still remains when editing a payoutMod—the initial value doesn't populate. Looks like the initialValue is undefined when it shouldn't be, so probably not a bug in your code.
> 
> After poking around a bit, it seems like an issue with how the initialValue is being passed from ProjectPayoutMods. If you wanna take a look at it you might be able to work in a fix with this PR, otherwise I'll start working on it separately later tonight

**Comment by peripheralist** [comment]
> Copying comment from issue ([#119 (comment)](https://github.com/jbx-protocol/juice-interface/issues/119#issuecomment-982075205))

glad you found this! put it in the wrong place obviously.

**Comment by peripheralist** [comment]
@aeolianeth try rebasing this against main. just pushed a patch that now makes sure the projectId is passed to the projectHandle form item.

File: src/components/shared/formItems/ProjectHandle.tsx (hunk 6 above)
Comment (aeolianeth) [reply src/components/shared/formItems/ProjectHandle.tsx:33]: https://github.com/jbx-protocol/juice-interface/issues/243 👍

**Comment by jnoh** [comment]
Linking: https://github.com/jbx-protocol/juice-interface/issues/189

**Comment by aeolianeth** [comment]
@jnoh thanks for much for identifying the fix to https://github.com/jbx-protocol/juice-interface/issues/189. I took inspiration from your PR and added a bit of extra logic so we show the green tick when a project doesn't change their handle.

Let me know what you think!

https://github.com/jbx-protocol/juice-interface/pull/241/commits/d91fcbe172ba5af82d44fb6a4aa00a105a452b0d

**Comment by aeolianeth** [comment]
@peripheralist thanks for the projectId fix! Rebased and good to go.

I also added an extra commit https://github.com/jbx-protocol/juice-interface/commit/d91fcbe172ba5af82d44fb6a4aa00a105a452b0d thanks to @jnoh's insights (to fix https://github.com/jbx-protocol/juice-interface/issues/189)🤝

**Comment by peripheralist** [comment]
sweet! would be great to solve both these in this PR. playing with this i still don't see the handle populate, though guessing the value is there since the suffix shows a green check mark. haven't looked into the code 
image

**Comment by peripheralist** [comment]
also just a heads up, a lot of Fleek builds have been failing lately due to what looks like something on their end. hoping that gets resolved soon

**Comment by aeolianeth** [comment]
@peripheralist sorry about that! Think I missed something during the rebase 🙈 .

99% sure everything is gucci now. Here's 2 videos to demonstrate:

### Fix for #119:

https://user-images.githubusercontent.com/94939382/144166927-3a8288cf-27d2-4407-a448-c4700f6b5c4c.mp4

### Fix for #189:

https://user-images.githubusercontent.com/94939382/144167102-0839b1b9-9fa4-4997-b56a-32cba42eab95.mp4

Let me know what you think 🙏

**Comment by peripheralist** [comment]
seems like there are some deeper bugs here. seems like this is working fine from the create form, but it doesn't work when editing existing payouts. 

maybe related to how the projectID is being passed to the ProjectPayoutMods form?

For details and discussion space check out payout-errorgardener-fc22 

https://user-images.githubusercontent.com/79433522/144299383-a20fd465-a34f-45f6-bba7-b80469b6e189.mov

**Comment by aeolianeth** [comment]
@peripheralist ah I see! Thanks for the demo video 🙏 

This one is turning out to be a bit of a doozy. I've almost fixed everything in https://github.com/jbx-protocol/juice-interface/pull/241/commits/7b17e19e01c8ece78fe5868cf03b2db1a3a4bb00, however there's still an issue where the `useContractReader` is triggered too many times, causing the loading state to appear too frequently.

I'll keep working on this, but if you have a chance, please feel free to have a play and see if you can find a quick fix.

**Comment by aeolianeth** [comment]
@peripheralist happy to say that I think I've finally figured this out.

Because of the "magic" binding that `Antd`'s `Form.Item` does, the solution was to use a custom input component ([kinda described in their docs](https://ant.design/components/form/#components-form-demo-customized-form-controls)). This approach allows us to "break" the binding and create a unidirectional data flow from `input` _up_ to `form.item`; our custom input doesn't accept a value prop, so `form.item` can't influence it.

There's a few other minor improvements here and there, and I've identified a few others that I'll put in seperate PRs.

Note that I didnt test `TokenRefs` on the Edit Tracked Assets modal as I didn't know how 🙈 .

Let me know what you think 🙏 

### Create project
https://user-images.githubusercontent.com/94939382/144680592-ff5d868e-d3f0-49b2-bf8f-82ebfdb8e33d.mp4

### Edit Project
https://user-images.githubusercontent.com/94939382/144680641-33fbbea5-64d0-4ad0-a82f-6693c4c01a7e.mp4

### Edit Payouts
https://user-images.githubusercontent.com/94939382/144680696-98add718-e911-4336-90fb-a1d94bf33084.mp4

cc @jnoh

**Review by peripheralist — APPROVED** [review]
nice detective work! that custom input `value` behavior is helpful to know. 

this is working great, thanks for spending so much time on this 🙏
