### PR TITLE
fix: project settings mint rate changes to original bug

### LINKED ISSUE #4246: [CRITICAL] Weight incorrectly set to zero, leading to incorrect project configuration
<@&1203035234472435712> artizen's current issuance rate is 180 tokens per ETH, and its issuance reduction rate is 10% https://juicebox.money/v2/p/587

The owner queued a new cycle. The total issuance rate was pre-filled to 162 (90% of the current issuance rate, with the issuance reduction rate applied). He wanted to cancel this out by explicitly setting the issuance rate back to 180 tokens per ETH (the current value).

However, his transaction was encoded with a weight of 0. This means that the issuance reduction rate WILL apply (incorrectly)

https://discord.com/channels/775859454780244028/1204557215030321293

### PR DESCRIPTION
**Pull request by johnnyd-eth**
Fixes #4246  (refer to **Case 2** below):

### Case 1: Mint rate unchanged
i.e. Inputted mint rate is the same as what would be applied by the discount rate.
-> Sends 0 to contracts:

Screen Shot 2024-02-07 at 11 52 50 am

### Case 2: Mint rate changes to anything else (including to current FC's mint rate):
-> Sends the value inputted to the contracts

Artizen's issue is that they set the mint rate back to current FC's mint rate, which was mistakenly also giving 0 to the contracts. The video below shows me executing the same process with JB's cycle with success:

https://github.com/jbx-protocol/juice-interface/assets/96150256/71409821-4a2a-4ecf-a92d-8862f51b18ce

### Case 3: User sets mint rate to 0:
-> As before, contracts need to see a value of `1`. This is unchanged:
Screen Shot 2024-02-07 at 12 06 05 pm

### CODE REVIEW

File: src/components/v2v3/V2V3Project/V2V3ProjectSettings/hooks/useReconfigureFundingCycle.ts [hunk 1]
```diff
@@ -110,8 +114,11 @@ export const useReconfigureFundingCycle = ({
         : editingFundingCycleMetadata
 
       const weight = getWeightArgument({
-        currentFundingCycleWeight: fundingCycle.weight,
-        newFundingCycleWeight: editingFundingCycleData.weight,
+        currentWeightAfterDiscountRate: deriveNextIssuanceRate({
```
Comment (johnnyd-eth) [inline src/components/v2v3/V2V3Project/V2V3ProjectSettings/hooks/useReconfigureFundingCycle.ts:117]: This function is an incredible bong but used in a bunch of other places, so I don't think it's worth reworking.

Comment (johnnyd-eth) [reply src/components/v2v3/V2V3Project/V2V3ProjectSettings/hooks/useReconfigureFundingCycle.ts:117]: But basically, if given these arguments, it gives back that derived mint rate reliably.

File: src/components/v2v3/V2V3Project/V2V3ProjectSettings/pages/EditCyclePage/ReviewConfirmModal/hooks/useTokensSectionValues.ts [hunk 2]
```diff
@@ -74,9 +70,7 @@ export const useTokensSectionValues = () => {
       }),
     )
 
-  const mintRateHasDiff = Boolean(
-    currentMintRateNum !== newMintRateNum && !onlyDiscountRateApplied,
```
Comment (johnnyd-eth) [inline src/components/v2v3/V2V3Project/V2V3ProjectSettings/pages/EditCyclePage/ReviewConfirmModal/hooks/useTokensSectionValues.ts:78]: This was the main problem, looking at both the ` !onlyDiscountRateApplied` AND `current === new`. Second condition not necessary.

File: src/components/v2v3/V2V3Project/V2V3ProjectSettings/pages/EditCyclePage/ReviewConfirmModal/TokensSectionDiff.tsx [hunk 3]
```diff
@@ -58,11 +63,16 @@ export function TokensSectionDiff() {
...
+    weight: BigNumber.from(0),
+    previousFC: currentFundingCycle,
+  })
+
   return (
     <DiffSection
       content={
         <div className="mb-5 flex flex-col gap-3 text-sm">
-          {mintRateHasDiff && currentMintRate && (
+          {mintRateHasDiff && currentMintRateAfterDiscountRateApplied && (
```
Comment (johnnyd-eth) [inline src/components/v2v3/V2V3Project/V2V3ProjectSettings/pages/EditCyclePage/ReviewConfirmModal/TokensSectionDiff.tsx:75]: This needed changing, otherwise in that Artizen case, you end up with "Old value: 101" and "New value: 101". This way, we set the old value to be diffed to the current mintRate after discountRate applied.

File: src/components/v2v3/V2V3Project/V2V3ProjectSettings/pages/EditCyclePage/ReviewConfirmModal/TokensSectionDiff.tsx [hunk 4]
```diff
@@ -58,11 +63,16 @@ export function TokensSectionDiff() {
 
   const formattedReservedRate = parseFloat(formatReservedRate(newReservedRate))
 
+  const currentMintRateAfterDiscountRateApplied = deriveNextIssuanceRate({
+    weight: BigNumber.from(0),
```
Comment (tomquirk) [inline src/components/v2v3/V2V3Project/V2V3ProjectSettings/pages/EditCyclePage/ReviewConfirmModal/TokensSectionDiff.tsx:67]: maybe a comment here to say wahts goin on.

maybe even pull this out into a function an reuse it in these 2 spots. Want to contain the confusion if possible

**Review by tomquirk — APPROVED** [review]
